### ISSUE TITLE
How to upgrade from an older version of the EFI

### ISSUE THREAD

**Issue by AlienKevin** [adityabakare/macOS-Dell-Latitude-E7470#11]
I installed macOS Big Sur using an older version of the EFI in this repo. Is there a way for me to upgrade to use the new EFI? Do I have to reinstall macOS from scratch?

**Comment by adityabakare** [comment]
No you don't have to reinstall it. Just mount your EFI partition using [MountEFI](https://github.com/corpnewt/MountEFI), and replace your existing EFI folder with the latest one available over here.
