### ISSUE TITLE
Question: How to Get HDMI when using DVI adapter

### ISSUE THREAD

**Issue by jtitley** [adityabakare/macOS-Dell-Latitude-E7470#17]
Anyone knows how to make DVI adapter work. I confirmed HDMI straight works, but my monitor is DVI. Weird that my other hackintosh's don't have this problem.

**Comment by adityabakare** [comment]
Since we don't have a dedicated DVI port, I don't feel like I should be flagging this as an issue. Moreover, as this is a question, I'm moving this to Discussions for others to discuss and try to resolve any doubts.
