### ISSUE TITLE
Lightsensor.kext

### ISSUE THREAD

**Issue by PPPPPH** [adityabakare/macOS-Dell-Latitude-E7470#24]
I dont find the ambient light sensor in Windows,is that kext a useless one? Opencore guide says Do not use if you don't have an ambient light sensor, can cause issues otherwise.

**Comment by adityabakare** [comment]
[According to OpenCore](https://github.com/acidanthera/OpenCorePkg/blob/b3f19f982d390e5de86e837917502b944d7bcfc8/Docs/AcpiSamples/Source/SSDT-ALS0.dsl#L2), macOS should report light sensor values to the SMC from 10.15 onwards. Our hardware doesn't have a light sensor, so I've used SSDT-ALS0, which reports dummy values to the SMC, in case the hardware doesn't have an ambient light sensor.

**Comment by PPPPPH** [comment]
Thanks a lot
