### ISSUE TITLE
trackpad is laggy

### ISSUE THREAD

**Issue by MuhammadMostey** [adityabakare/macOS-Dell-Latitude-E7470#27]
Dear I really want your help I have 2 issues until now, please advise 

First Issue: my trackpad been laggy after I installed Big Sur with the EFI file you used, my hardware same as yours only the processor is I5. I've tried with external usb mouse it's work fine but when the laptop is plugged to the charger my trackpad at first touch move few pixels the freeze and become very laggy until I disconnect the charger return normal

Second Issue: when my screen go off its freeze without showing anything even if I tried to press any key or move mouse around, when I tried to reduce the screen brightness as well its not function and its again screen goes off and it not work back until I press on my laptop keyboard for putting the lap in sleep mode and again I press the power button until its back slowly.

**Comment by adityabakare** [comment]
Have you made any changes to the VoodooPS2 kext?

Also, since you have an i5 variant, you need to generate your own set of CPUFriendDataProvider.kext and SSDT-DATA.aml using CorpNewt's CPUFriendFriend tool.

**Comment by MuhammadMostey** [comment]
Thanks for your reply on that, I have not did any changes to the VoodooPS2 kext or any of the others.
And regarding my CPU model is I5-6300U, I've tried one way following a guide on how to generate the CPUFriendDataProvider.kext and the SSDT-DATA using CPUFriend command file, and once its generated I did place both files in the EFI folder ACPI and Kexts, and then, I have done the mounting to the updated files in the config list as well, but my laptop won't boot once I did restarted my laptop then I just used my bootable usb to get access in the system and did get the previous efi agin

**Comment by adityabakare** [comment]
Maybe some logs would help. Because there seem to be no issues over here, and also others who are using it.

**Comment by MuhammadMostey** [comment]
I will update if there is any problem, thanks for your time.
