### ISSUE TITLE
Laptop Dell Latitude E7470 - Freezing Plugging/unplugging the power adapter

### ISSUE THREAD

**Issue by abel3t** [adityabakare/macOS-Dell-Latitude-E7470#3]
Freezing by Plugging/unplugging the power adapter.

- BootLoader: OpenCore v0.6.3
- OS: Catalina 10.15.7

**Comment by adityabakare** [comment]
I haven't updated my EFI to OC v0.6.3 yet, so if you've done it by yourself, I can't help you with that. Also, I need more information, like your plist file, the kexts you're using along with their versions, etc. I'll keep the issue open until I update the EFI.

**Comment by adityabakare** [comment]
Updated the EFI to OC 0.6.3, and there seems to be no issue of freezing while plugging/unplugging the power adapter. Therefore, closing this issue.
