### ISSUE TITLE
Only Openshell.efi is visible during boot

### ISSUE THREAD

**Issue by AlienKevin** [adityabakare/macOS-Dell-Latitude-E7470#5]
## Problem
`OpenCore.efi` is not visible during boot on E7470. Only `Openshell.efi` is visible.

## My solution
set `ScanPolicy` in `config.plist` to `0`

See [this reddit thread](https://www.reddit.com/r/hackintosh/comments/h0lgwe/help_stuck_on_the_openshellefi_boot_option/)

**Comment by adityabakare** [comment]
I partially commited what I had to change, and pushed in a hurry. Will fix this and push the remaining changes too.

**Comment by adityabakare** [comment]
This has been dealt with.
