### ISSUE TITLE
Computer freezes when copying files from one external exFAT drive to another

### ISSUE THREAD

**Issue by AlienKevin** [adityabakare/macOS-Dell-Latitude-E7470#8]
When I tried to copy some files (totalling around 40gb) from one exFAT drive to another external exFAT drive, the copy process ended up freezing the whole computer (only mouse is movable) after a few minutes. Only restarting solved the issue. I tried this two times and each time it froze after a few minutes.

**Comment by adityabakare** [comment]
Since I don't have an ExFAT drive or partition to test, I cannot reproduce this issue. Also, some logs will help me investigate further.

**Comment by AlienKevin** [comment]
Maybe you can replicate this by formatting two USBs as exFAT. How can I record a log during file copy?

**Comment by adityabakare** [comment]
Theres Console App for logging via UI. Or you can grab logs from the terminal. After capturing them, paste them into a paste service like PasteBin or DogBin, and post a link over here.

**Comment by AlienKevin** [comment]
Ok. I'm a bit lazy to redo this whole process. The new updated EFI feels smoother to me so I guess this issue may be resolved.
